#!/usr/bin/env python
import time
from zeroconf import ServiceBrowser, Zeroconf

class STListener( object ):
    def remove_service( self, zeroconf, type, name ):
        print "service name: %s - remove called" % name

    def add_service( self, zeroconf, type, name ):
        #print "========"
        #print "service name: %s - add called" % name
        info = zeroconf.get_service_info( type, name )
        #print "service info: %s" % info
        #print "%d.%d.%d.%d" % ( ord( info.address[0] ), ord( info.address[1] ), ord( info.address[2]  ), ord( info.address[3] ) )
        print "%d" % ( ord( info.address[3] ) )
        #print

zeroconf = Zeroconf()
listener = STListener()
browser = ServiceBrowser( zeroconf, "_soundtouch._tcp.local.", listener )
time.sleep( 2 )
zeroconf.close()
