#!/bin/bash

IP=$1

if [ "x${IP}" == "x" ]; then
    echo "Usage: $0 <IP>"
    exit
fi

curl -s http://${IP}:8090/info | xmllint --format - | grep softwareVersion | cut -d'>' -f 2 | cut -d'<' -f1 | grep epdbuild | cut -d' ' -f1
